ports:
    http: 8080
    debug: 5858

auth:
    jwt_secret: 'supersecret'

spec:
    weather: 'http://api.selectedwork.de/v1/weather/swagger.json'

mongo:
    url: 'mongodb://mongo:27017'

# none/debug/info
loglevel: info